import { test, expect } from '@playwright/test';

test.describe('Contact and Newsletter Flows', () => {
  test('User can submit a contact form', async ({ page }) => {
    await page.goto('/contact');
    
    await page.fill('input[name="name"]', 'John Doe');
    await page.fill('input[name="email"]', 'johndoe@example.com');
    await page.fill('input[name="subject"]', 'Inquiry from E2E tests');
    await page.fill('textarea[name="message"]', 'This is a test message generated by Playwright.');

    await page.click('button[type="submit"]');

    // Wait for success message (could be a toast or a UI state change)
    await expect(page.locator('text=Message sent successfully').or(page.locator('text=Thank you for contacting us'))).toBeVisible({ timeout: 10000 });
  });

  test('User can subscribe to the newsletter', async ({ page }) => {
    // Newsletter is usually in the Footer
    await page.goto('/');

    const newsletterInput = page.locator('input[placeholder*="email"][type="email"]');
    if (await newsletterInput.isVisible()) {
      await newsletterInput.fill(`subscriber${Date.now()}@example.com`);
      await page.click('button:has-text("Subscribe")');

      // Expect some success feedback
      await expect(page.locator('text=Subscribed successfully').or(page.locator('text=Thanks for subscribing!'))).toBeVisible({ timeout: 10000 });
    }
  });
});
